title: "Abhijnan Nath"
description: "AI/NLP Researcher | PhD Student | Publications and Projects"
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme # Ensure this plugin is enabled
header_pages:
  - publications.md
google_analytics: G-0WRNB6ZHTP
